### ISSUE TITLE
关于数据预处理，求大佬解答

### ISSUE THREAD

**Issue by yinwang950613** [leeyeehoo/SiamVGG#12]
大佬，能问下这个ilsvrc_vid.txt and youtube_final.txt是怎么生成的吗？

**Comment by leeyeehoo** [comment]
在dataset里面有ipynb

**Comment by yinwang950613** [comment]
那为什么在训练的时候，就是运行traning代码的时候，还需要download checkpoint.pth.tar?

**Comment by leeyeehoo** [comment]
那个是load pretrained vggnet 的参数 做transfer learning

**Comment by yinwang950613** [comment]
这样子啊，谢谢你！

**Comment by yinwang950613** [comment]
还有一个问题，既然是transfer learning ,那代码中的 mod = models.vgg16(pretrained = True)这个不就是把VGG的网络参数给自己定义的新的model吗？这两者有什么不一样呢？

**Comment by leeyeehoo** [comment]
等等。。。download checkpoint.pth.tar在哪一行？

**Comment by leeyeehoo** [comment]
我以为你说的是mod = models.vgg16(pretrained = True)

**Comment by yinwang950613** [comment]
就是在运行traning代码的时候，指令后面有个arg的参数  ，叫做 --pre 对吧，python train.py 0 SIAMVGG --pre='backup/bestSIAMVGG.pth.tar'  ，这个--pre是指所训练model的保存路径？还是说下载的vgg16的.pth，不太明白，因为我运行这个代码时会出现错误，IOError: [Errno 2] No such file or directory: 'backup/siamVGG_ywcheckpoint.pth.tar'

**Comment by yinwang950613** [comment]
Epoch: [0][119/125]	Time 0.278 (0.292)	Data 0.247 (0.258)	Loss 263.2892 (490.3870)	
Epoch: [0][120/125]	Time 0.312 (0.292)	Data 0.282 (0.259)	Loss 270.5379 (488.5701)	
Epoch: [0][121/125]	Time 0.286 (0.292)	Data 0.255 (0.259)	Loss 274.4255 (486.8148)	
Epoch: [0][122/125]	Time 0.291 (0.292)	Data 0.260 (0.259)	Loss 226.7929 (484.7008)	
Epoch: [0][123/125]	Time 0.290 (0.292)	Data 0.258 (0.259)	Loss 310.4707 (483.2957)	
Traceback (most recent call last):
  File "/home/tanjianhao/yinwang/procedure/SiamVGG-master/train/train.py", line 259, in <module>
    main()        
  File "/home/tanjianhao/yinwang/procedure/SiamVGG-master/train/train.py", line 136, in main
    }, is_best,args.task)
  File "/home/tanjianhao/yinwang/procedure/SiamVGG-master/train/utils.py", line 62, in save_checkpoint
    torch.save(state, 'backup/'+task_id+filename)
  File "/home/tanjianhao/anaconda3/envs/pytorch_py2.7/lib/python2.7/site-packages/torch/serialization.py", line 224, in save
Epoch: [0][124/125]	Time 0.298 (0.292)	Data 0.267 (0.259)	Loss 270.0476 (481.5897)	
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
 * best MAE 0.000 
  File "/home/tanjianhao/anaconda3/envs/pytorch_py2.7/lib/python2.7/site-packages/torch/serialization.py", line 147, in _with_file_like
 * MAE 0.000 
    f = open(f, mode)
IOError: [Errno 2] No such file or directory: 'backup/siamVGG_ywcheckpoint.pth.tar'

**Comment by yinwang950613** [comment]
当运行traning之后，开始会出现训练的迭代的信息，但是在epoch[0]迭代到123的时候，就会报错，no such file or dirrectory: ...

**Comment by leeyeehoo** [comment]
你要新建一个目录叫backup.

**Comment by fAnchao1** [comment]
@leeyeehoo 为什么我直接用你的vgg网络去替换alexnet进行训练得到的loss是nan呢（siamfc代码用的是别人的）

**Comment by nosaydomore** [comment]
请问VID是2015还是2017

**Comment by Huang9495** [comment]
@yinwang950613 what the first number and the end number of you loss in training siamVGG?

**Comment by wg7stream** [comment]
> 大佬，能问下这个ilsvrc_vid.txt and youtube_final.txt您有吗，我对数据预处理这块不太懂，能够分享一下您的.txt文件。
