### ISSUE TITLE
code problems

### ISSUE THREAD

**Issue by SaintLogos1234** [leeyeehoo/SiamVGG#7]
I came across this code while reading your source code：
```
for i in xrange(len(self.model.state_dict().items())):
            self.model.state_dict().items()[i][1].data[:] = mod.state_dict().items()[i][1].data[:]
```
(model,py)
What does it do

**Comment by SaintLogos1234** [comment]
when I run :python train.py 0 SIAMVGG --pre='backup/bestSIAMVGG.pth.tar', The following error occurs：
```
Traceback (most recent call last):
  File "train.py", line 264, in <module>
    main()        
  File "train.py", line 78, in main
    model = SiameseNet()
  File "/home/xieyangyang/Downloads/SiamVGG-master/train/model.py", line 46, in __init__
    self.model.state_dict().items()[i][1].data[:] = mod.state_dict().items()[i][1].data[:]
RuntimeError: The expanded size of the tensor (1) must match the existing size (3) at non-singleton dimension 3
```

**Comment by leeyeehoo** [comment]
It copy the vgg pretrained weight from pytorch model zoo to the model.

**Comment by leeyeehoo** [comment]
You can print it out to debug.

**Comment by SaintLogos1234** [comment]
I read your code siamvgg, siamrpnvgg clearly, I find problems I find the problem lies in your network model architecture：

- self.model = nn.Sequential(
-             nn.Conv2d(3, 64, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(64, 64, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),
-             nn.Conv2d(64, 128, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(128, 128, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),            
-             nn.Conv2d(128, 256, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(256, 256, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(256, 256, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),            
-             nn.Conv2d(256, 512, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(512, 512, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(512, 512, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(512, 256, kernel_size=1, stride=1),
-         )

```
self.model = nn.Sequential(
-             nn.Conv2d(3, 64, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(64, 64, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),
-             nn.Conv2d(64, 128, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(128, 128, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),            
-             nn.Conv2d(128, 256, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(256, 256, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(256, 256, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),            
-             nn.Conv2d(256, 512, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(512, 512, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             nn.Conv2d(512, 512, kernel_size=3, stride=1),
-             nn.ReLU(inplace=True),
-             #nn.Conv2d(512, 256, kernel_size=1, stride=1),
-         )
        self.backend = nn.Sequential(nn.Conv2d(512, 256, kernel_size=1, stride=1))
```

**Comment by SaintLogos1234** [comment]
python train.py 0 SIAMVGG --pre='backup/bestSIAMVGG.pth.tar'
```
/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
=> no checkpoint found at 'backup/bestSIAMVGG.pth.tar'
epoch 0, processed 0 samples, lr 0.0000100000
Traceback (most recent call last):
  File "train.py", line 264, in <module>
    main()        
  File "train.py", line 112, in main
    train( model, criterion, optimizer, epoch,coco)
  File "train.py", line 158, in train
    for i,(z,x,template,gt_box)in enumerate(train_loader):
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/xieyangyang/Downloads/SiamVGG-master/SiamVGG-master/train/dataset.py", line 71, in __getitem__
    template = self.transform(template)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The expanded size of the tensor (28) must match the existing size (3) at non-singleton dimension 0
```

**Comment by SaintLogos1234** [comment]
I have one more question for you. What's the version of your pytorch

**Comment by leeyeehoo** [comment]
0.4.0. Where is bestSIAMVGG came from? Did you train that?

**Comment by SaintLogos1234** [comment]
The following error occurred in my operation according to the instructions of your training readme.md:
```
/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
=> no checkpoint found at 'backup/bestSIAMVGG.pth.tar'
epoch 0, processed 0 samples, lr 0.0000100000
Traceback (most recent call last):
  File "train.py", line 267, in <module>
    main()        
  File "train.py", line 115, in main
    train( model, criterion, optimizer, epoch,coco)
  File "train.py", line 161, in train
    for i,(z,x,template,gt_box)in enumerate(train_loader):
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/xieyangyang/Downloads/SiamVGG-master/SiamVGG-master/train/dataset.py", line 71, in __getitem__
    template = self.transform(template)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The expanded size of the tensor (28) must match the existing size (3) at non-singleton dimension 0

```
I read your code, Locate where the error should have occurred：dataset.py 71 line, what can I do ?

**Comment by SaintLogos1234** [comment]
Sorry for asking such a stupid question, I found that it seems that the main reason for this problem is that I changed your code, I made a new copy and ran it as if it was ok
